services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2182
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10

  backend-python:
    build: python
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      FRONT_URL: "http://localhost:3000"
    volumes:
      - images:/app/images

  frontend:
    build:
      context: typescript/simple-mercari-web
      args:
        VITE_BACKEND_URL: "http://localhost:9000"
    ports:
      - "3000:3000"

volumes:
  images: